# Site settings
title: inTheLight
email: wansooha@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Soli Deo Gloria
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pkgpl.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  pkgpl
encoding: utf-8

# Build settings
markdown: kramdown
#highlighter: pygments

# Google analytics
google_analytics: UA-85000918-1

# gems
gems:
  - jekyll-seo-tag

# Disqus post comments
disqus_shortname: pkgpl

# Collctions
#collections:
#  publications:
#    output: true
#    permalink: /publications/:path/
#  classes:
#    output: true
#    permalink: /classes/:path/

# Default values
defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

