# Site settings
title: PKGPL
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Pukyong National University
  Geophysical Prospecting Lab.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pkgpl.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  pkgpl

# Build settings
markdown: kramdown

# Google analytics
google_analytics: UA-85000918-1
