# Site settings
title: PKGPL
email: wansooha@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Geophysical Prospecting Lab. <br>
Pukyong National University
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pkgpl.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  pkgpl

# Build settings
markdown: kramdown

# Google analytics
google_analytics: UA-85000918-1

# Disqus post comments
disqus_shortname: pkgpl
